# Generated by Django 3.1 on 2021-03-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradores',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='email'),
        ),
    ]
