# Generated by Django 3.1 on 2021-03-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_compradores_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradores',
            name='estado_geo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estado geo'),
        ),
        migrations.AlterField(
            model_name='compradores',
            name='latitud',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='compradores',
            name='longitud',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitud'),
        ),
    ]
